from enum import StrEnum

class UserRole(StrEnum):
    operator = "operator"
    admin = "admin"

class CommandStatus(StrEnum):
    pending = "pending"
    running = "running"
    done = "done"
    failed = "failed"

class Severity(StrEnum):
    info = "info"
    warn = "warn"
    error = "error"

class SystemMode(StrEnum):
    idle = "idle"
    manual = "manual_running"
    auto_running = "auto_running"
    paused_safety = "paused_safety"
    paused_rejectbin = "paused_rejectbin"
    paused_trash_missing = "paused_trash_missing"
    paused_temperature = "paused_temperature"
    paused_no_air = "paused_no_air"
    paused_operator = "paused_operator"
    error = "error"

class CommandType(StrEnum):
    PING = "PING"
    START_AUTO = "START_AUTO"
    STOP_AUTO = "STOP_AUTO"
    PAUSE_SYSTEM = "PAUSE_SYSTEM"
    RESUME_SYSTEM = "RESUME_SYSTEM"
    REPLACE_REJECTBIN = "REPLACE_REJECTBIN"

    SET_EMERGENCY_SOUND_MUTED = "SET_EMERGENCY_SOUND_MUTED"

    RTK_START = "RTK_START"
    RTK_STOP = "RTK_STOP"
    RTK_RESET = "RTK_RESET"
    RTK_PAUSE = "RTK_PAUSE"
    RTK_RESUME = "RTK_RESUME"
    RTK_CYCLE_ON = "RTK_CYCLE_ON"
    RTK_SET_STEP_MODE = "RTK_SET_STEP_MODE"
    RTK_NEXT_STEP = "RTK_NEXT_STEP"    
    RTK_CALIBRATE = "RTK_CALIBRATE"
    RTK_SETSPEED = "RTK_SETSPEED"
    RTK_SENDMEASUREMENTRESULT = "RTK_SENDMEASUREMENTRESULT"
    RTK_SENDCALIBRATIONRESULT = "RTK_SENDCALIBRATIONRESULT"

    IM_MEASUREMENT_RESULT = "IM_MEASUREMENT_RESULT"
    IM_CALIBRATION_RESULT = "IM_CALIBRATION_RESULT"    

    # IM (ручные процедуры из админки)
    IM_CLEAR_DB = "IM_CLEAR_DB"
    IM_VACUUM_ON = "IM_VACUUM_ON"
    IM_VACUUM_OFF = "IM_VACUUM_OFF"
    IM_LOAD_PROGRAM = "IM_LOAD_PROGRAM"
    IM_CALIBRATE = "IM_CALIBRATE"
    IM_MEASURE_ONCE = "IM_MEASURE_ONCE"

    SET_ACTIVE_BATCH = "SET_ACTIVE_BATCH"
    MARK_ACTIVE_BATCH_EXTRACTED = "MARK_ACTIVE_BATCH_EXTRACTED"

    PRINT_DOCS = "PRINT_DOCS"    

    POSTAMAT_OPEN_LOADING_CELL = "POSTAMAT_OPEN_LOADING_CELL"
    POSTAMAT_OPEN_UNLOADING_CELL = "POSTAMAT_OPEN_UNLOADING_CELL"
    CHECK_BATCH_EXTRACTION_DOORS = "CHECK_BATCH_EXTRACTION_DOORS"

class EventType(StrEnum):
    DAEMON_STARTED = "DAEMON_STARTED"
    COMMAND_ACCEPTED = "COMMAND_ACCEPTED"
    COMMAND_DONE = "COMMAND_DONE"
    COMMAND_FAILED = "COMMAND_FAILED"
    PONG = "PONG"
    AUTO_STARTED = "AUTO_STARTED"
    AUTO_STOPPED = "AUTO_STOPPED"
    AUTO_TICK = "AUTO_TICK"

    SYSTEM_PAUSED = "SYSTEM_PAUSED"
    SYSTEM_RESUMED = "SYSTEM_RESUMED"
    SAFETY_TRIPPED = "SAFETY_TRIPPED"
    REJECTBIN_FULL = "REJECTBIN_FULL"
    REJECTBIN_REPLACED = "REJECTBIN_REPLACED"
    REJECTBIN_REPORT_PRINTED = "REJECTBIN_REPORT_PRINTED"
    REJECTBIN_ITEM_ADDED = "REJECTBIN_ITEM_ADDED"
    TRASHCAN_MISSING = "TRASHCAN_MISSING"
    TRASHCAN_RESTORED = "TRASHCAN_RESTORED"
    REJECTBIN_NEAR_FULL = "REJECTBIN_NEAR_FULL"
    SIGNALS_APPLIED = "SIGNALS_APPLIED"
    RTK_COMMAND_SENT = "RTK_COMMAND_SENT"
    RTK_SNAPSHOT = "RTK_SNAPSHOT"

    MEASUREMENT_RECORDED = "MEASUREMENT_RECORDED"
    CALIBRATION_REQUESTED = "CALIBRATION_REQUESTED"
    CALIBRATION_RESULT_RECORDED = "CALIBRATION_RESULT_RECORDED"

    IM_VACUUM_SET = "IM_VACUUM_SET"
    IM_PROGRAM_LOADED = "IM_PROGRAM_LOADED"
    IM_CALIBRATION_STARTED = "IM_CALIBRATION_STARTED"
    IM_MEASUREMENT_STARTED = "IM_MEASUREMENT_STARTED"

    POSTAMAT_CELL_OPEN_REQUESTED = "CELL_OPEN_REQUESTED"
    DOCS_PRINTED = "DOCS_PRINTED"
    REJECTBIN_DOOR_OPEN_REQUESTED = "REJECTBIN_DOOR_OPEN_REQUESTED"

    BATCH_CREATED = "BATCH_CREATED"
    BATCH_REJECTED = "BATCH_REJECTED"
    BATCH_REPORT_PRINTED = "BATCH_REPORT_PRINTED"
    BATCH_EXTRACTED = "BATCH_EXTRACTED"
    BATCH_DONE = "BATCH_DONE" 

    TEMPERATURE_OUT_OF_RANGE = "TEMPERATURE_OUT_OF_RANGE"
    TEMPERATURE_NEAR_CRITICAL = "TEMPERATURE_NEAR_CRITICAL"
    TEMPERATURE_UNAVAILABLE = "TEMPERATURE_UNAVAILABLE"    

    ERROR = "ERROR"
    STATE_UPDATED = "STATE_UPDATED"

    SETTINGS_UPDATED = "SETTINGS_UPDATED"

    USER_LOGIN = "USER_LOGIN"
    USER_LOGOUT = "USER_LOGOUT"

    OPERATOR_CREATED = "OPERATOR_CREATED"
    OPERATOR_DISABLED = "OPERATOR_DISABLED"

    EXPORT_CREATED = "EXPORT_CREATED"
    EXPORT_FAILED = "EXPORT_FAILED"
    USB_UNMOUNTED = "USB_UNMOUNTED"
    USB_UNMOUNT_FAILED = "USB_UNMOUNT_FAILED"
    
    
